build:
  image: node:6
  working_dir: /srv/app
  volumes:
    - .:/srv/app
  environment:
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - GITHUB_RELEASE_ACCESS_TOKEN
    - DOCKER_HUB_TRIGGER_TOKEN
    - SSH_AUTH_SOCK=/ssh-agent
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
