export const PREFIXABLE_PROPS = [
  'accelerator',
  'animation',
  'appearance',
  'aspectRatio',
  'backdropFilter',
  'backfaceVisibility',
  'backgroundComposite',
  'binding',
  'blockProgression',
  'borderAfter',
  'borderBefore',
  'borderEnd',
  'borderFit',
  'borderStart',
  'borderVerticalSpacing',
  'box',
  'column',
  'filter',
  'flex',
  'flow',
  'fontFeatureSettings',
  'fontSizeDelta',
  'fontSmoothing',
  'grid',
  'hyphenate',
  'hyphens',
  'imageRegion',
  'initialLetter',
  'line',
  'locale',
  'logical',
  'marginAfter',
  'marginBefore',
  'marginBottomCollapse',
  'marginCollapse',
  'marginEnd',
  'marginFit',
  'marginStart',
  'marginTopCollapse',
  'marquee',
  'mask',
  'math',
  'objectFit',
  'perspective',
  'scrollSnap',
  'textAlignLast',
  'textDecoration',
  'textFill',
  'textJustify',
  'textOrientation',
  'textSecurity',
  'textSizeAdjust',
  'textStroke',
  'textUnderline',
  'textZoom',
  'textOverflow',
  'transform',
  'userSelect',
  'wordBreak',
  'wrap'
]

export const ALTERNATE_PROPS = {
  alignContent: 'msFlexLinePack',
  alignSelf: 'msFlexItemAlign',
  alignItems: 'msFlexAlign',
  justifyContent: 'msFlexPack',
  order: 'msFlexOrder',
  flexGrow: 'msFlexPositive',
  flexShrink: 'msFlexNegative',
  flexBasis: 'msPreferredSize'
}

export const PREFIXABLE_VALUES = [
  'grid',
  'inline-grid',
  'linear-gradient',
  'radial-gradient',
  'repeating-linear-gradient',
  'repeating-radial-gradient'
]

export const ALTERNATE_VALUES = {
  'break-all': ['break-word'],
  'flex': ['-webkit-box', '-ms-flexbox', '-webkit-flex'],
  'flex-end': ['end'],
  'flex-start': ['start'],
  'space-around': ['distribute'],
  'space-between': ['justify']
}
