export {default as logo} from '../images/standard.svg'
export {default as logoInverted} from '../images/inverted.svg'
export {default as mark} from '../images/mark-standard.svg'
export {default as markInverted} from '../images/mark-inverted.svg'
export {default as poweredBy} from '../images/powered-by.svg'
export {default as poweredByInverted} from '../images/powered-by-inverted.svg'
