---
steps:

  - label: ":docker: build image"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: native
      docker: builder

  - wait

  - label: ":shipit: Deploy experience docs"
    command: "bin/buildkite bin/ci run bin/deploy-experience-docs"
    agents:
      queue: elastic
