---
steps:

  - label: ":docker: build image"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: build

  - wait

  - label: ":mocha: Unit Tests"
    command: "bin/buildkite bin/ci run bin/units"

  - wait

  - label: ":shipit: Deploy experience docs"
    command: "bin/buildkite bin/ci run bin/deploy-experience-docs"
    branches: "master release/*"
